markdown: markdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: pingangit
author: "康晓宁"
email: kxnmei#163.com
name: "康晓宁个人博客"
url: http://pingangit.github.io
domain: pingangit.github.io
all_categories: [
["python", "Python","/posts/python.html"],
["linux", "Linux","/posts/linux.html"],
["Saltstack", "saltstack","/posts/saltstack.html"],
["web", "web","/posts/web.html"],
["security", "安全","/posts/security.html"],
["read", "读书笔记","/posts/read.html"],
["other", "杂记","/posts/other.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
